--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    ? 
      ? "include \"mychart.labels\" ."
      : ~
    : ~
  name: 
    ? 
      ? "include \"mychart.fullname\" ."
      : ~
    : ~
spec: 
  replicas: 
    ? 
      .Values.replicaCount: ~
    : ~
  selector: 
    matchLabels: 
      ? 
        ? "include \"mychart.selectorLabels\" ."
        : ~
      : ~
  template: 
    metadata: 
      labels: 
        ? 
          ? "include \"mychart.selectorLabels\" ."
          : ~
        : ~
    spec: 
      affinity: 
        ? 
          ? "toYaml ."
          : ~
        : ~
      containers: 
        - 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: 
            ? 
              .Values.image.pullPolicy: ~
            : ~
          livenessProbe: 
            httpGet: 
              path: /
              port: http
          name: 
            ? 
              .Chart.Name: ~
            : ~
          ports: 
            - 
              containerPort: 80
              name: http
              protocol: TCP
          readinessProbe: 
            httpGet: 
              path: /
              port: http
          resources: 
            ? 
              ? "toYaml .Values.resources"
              : ~
            : ~
          securityContext: 
            ? 
              ? "toYaml .Values.securityContext"
              : ~
            : ~
      nodeSelector: 
        ? 
          ? "toYaml ."
          : ~
        : ~
      securityContext: 
        ? 
          ? "toYaml .Values.podSecurityContext"
          : ~
        : ~
      serviceAccountName: 
        ? 
          ? "include \"mychart.serviceAccountName\" ."
          : ~
        : ~
      tolerations: 
        ? 
          ? "toYaml ."
          : ~
        : ~
